spring
  profiles:
    active:
    - dev
---
spring
  profiles: dev
  application:
    name: microservicecloud-config-cebbank-dev
---
spring
  profiles: test
  application: 
    name: microservicecloud-config-cebbank-test